'02-skeleton-v0'
js-tasks-ru/htmlcss-20210610_drdiz pull request #10
Opened 2021-06-23 06:07 UTC by DoppelGannger

created skeleton

2021-06-23 06:08 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-23 14:14 UTC, GSemikozov requested changes

2021-06-23 14:14 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__flex-box {
в качестве улучшения именования классов советую использовать вместо .skeleton__flex-box - просто .skeleton__box

2021-06-23 14:14 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__in-item {
.skeleton__in-item -> .skeleton__line

2021-06-23 14:14 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    display: block;
display: block; не обязательно задавать явно, такое значение будет и так по умолчанию

2021-06-23 14:14 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    margin: 8px 0;
margin  сверху / снизу скорее всего не всегда будет нужен?

2021-06-23 14:14 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    padding: 0;
мы уже выше сделали сброс отступов для .skeleton__flex-box - не стоит здесь и ниже дублировать

2021-06-23 14:14 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    flex: 1 1 100%;
здесь и ниже вместо flex: 1 1 100%; можно просто казать flex-grow: 1 на .skeleton__flex-box

2021-06-24 05:21 UTC, DoppelGannger commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__flex-box {
fix

2021-06-24 05:23 UTC, DoppelGannger commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__in-item {
вот это не совсем понятно(

2021-06-24 05:26 UTC, DoppelGannger commented on 04-lection2/02-skeleton/skeleton.css
> +    padding: 0;
fix

2021-06-24 05:29 UTC, DoppelGannger commented on 04-lection2/02-skeleton/skeleton.css
> +    flex: 1 1 100%;
не работает

2021-06-24 06:07 UTC, DoppelGannger commented on 04-lection2/02-skeleton/skeleton.css
> +    display: block;
fix

2021-06-24 06:26 UTC, DoppelGannger commented on 04-lection2/02-skeleton/skeleton.css
> +    flex: 1 1 100%;
блоки сжимаются и остаются в одной строке без basis 100%

2021-06-24 06:42 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-24 06:44 UTC, DoppelGannger commented on 04-lection2/02-skeleton/skeleton.css
> +    margin: 8px 0;
без отступов не корректно. только если наверное делать внутренний флекс

2021-06-24 08:02 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__in-item {
это к тому как переименовать класс)

2021-06-24 08:10 UTC, DoppelGannger commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__in-item {
fix

2021-06-24 08:14 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-24 08:16 UTC, GSemikozov requested changes

2021-06-24 08:16 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    flex: 1 1 100%;
окей, оставляем

2021-06-24 08:17 UTC, GSemikozov approved these changes

2021-06-24 08:17 UTC, merged