'main-page-v1-v0'
js-tasks-ru/htmlcss-20210610_drdiz pull request #12
Opened 2021-06-24 11:31 UTC by DoppelGannger

created next stage of build - index.html

2021-06-24 11:32 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-24 12:43 UTC, GSemikozov requested changes

2021-06-24 12:43 UTC, GSemikozov commented on components/main/main.css
> +.card-box {
.card-box - это отдельный компонент, его надо вынести в отдельный файл

2021-06-24 12:43 UTC, GSemikozov commented on components/main/main.css
> +    align-items: flex-start;
align-items: flex-start; align-content: flex-start; - значения по умолчанию, указывать не обязательно

2021-06-24 12:43 UTC, GSemikozov commented on components/main/main.css
> +    padding: 165px 68px 165px 204px;
такие. паддинги там точно не нужны, можно удалить)

2021-06-24 12:43 UTC, GSemikozov commented on components/main/main.css
> +    min-width: 350px;
уже есть значение flex-basis ниже, min-width не нужно прописывать

2021-06-24 12:43 UTC, GSemikozov commented on components/main/main.css
> +    margin-right: auto;
margin-right: auto;
padding: auto;

указывать не обязательно

2021-06-24 12:43 UTC, GSemikozov commented on components/main/main.css
> +    display: block;
display: block;
height: auto;
width: 100%;
    
указывать не обязательно, это значения по умолчанию

2021-06-24 12:43 UTC, GSemikozov commented on components/main/main.css
> +.card-box {
не вижу как через родителя или через дочерние элементы оформлены отступы между карточками

2021-06-24 12:54 UTC, DoppelGannger commented on components/main/main.css
> +.card-box {
fix

2021-06-24 12:54 UTC, DoppelGannger commented on components/main/main.css
> +    align-items: flex-start;
fix

2021-06-24 12:55 UTC, DoppelGannger commented on components/main/main.css
> +    padding: 165px 68px 165px 204px;
по фигме делал))))

2021-06-24 12:56 UTC, DoppelGannger commented on components/main/main.css
> +    padding: 165px 68px 165px 204px;
fix

2021-06-24 12:56 UTC, DoppelGannger commented on components/main/main.css
> +    min-width: 350px;
fix

2021-06-24 13:00 UTC, DoppelGannger commented on components/main/main.css
> +    display: block;
fix

2021-06-24 13:02 UTC, DoppelGannger commented on components/main/main.css
> +.card-box {
fix

2021-06-25 06:33 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-25 06:47 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-25 07:13 UTC, DoppelGannger commented on components/main/main.css
> +    margin-right: auto;
fix

2021-06-25 07:25 UTC, GSemikozov commented on components/main/main.css
> +    padding: 165px 68px 165px 204px;
да, но это было бы актуально если бы мы делали фиксированный и не адаптивный интерфейс)

2021-06-25 07:26 UTC, GSemikozov approved these changes

2021-06-25 07:26 UTC, merged