'radio-v0'
js-tasks-ru/htmlcss-20210610_drdiz pull request #19
Opened 2021-07-01 13:17 UTC by DoppelGannger

2021-07-01 13:17 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-07-01 13:29 UTC, GSemikozov requested changes

2021-07-01 13:29 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +    cursor: not-allowed
на disabled всегда лучше pointer-events: none

2021-07-01 13:29 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +    box-sizing: border-box;
уже определено выше

2021-07-01 13:29 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +    border-radius: 14px;
выше определено

2021-07-01 13:29 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +.radio-group {
строки 6-15 - это описание блока для внешней разметки радио-кнопок - нужно вынести из этого файла, тут должны быть стили только для блока, его элементов и модификаторов.

2021-07-05 05:57 UTC, DoppelGannger commented on 07-lection5/02-radio/radio.css
> +    cursor: not-allowed
fix

2021-07-05 05:59 UTC, DoppelGannger commented on 07-lection5/02-radio/radio.css
> +    border-radius: 14px;
fix

2021-07-05 06:00 UTC, DoppelGannger commented on 07-lection5/02-radio/radio.css
> +.radio-group {
fix

2021-07-05 06:07 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-07-06 04:50 UTC, DoppelGannger commented on 07-lection5/02-radio/radio.css
> +    box-sizing: border-box;
fix

2021-07-06 05:18 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-07-06 09:33 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-07-06 09:36 UTC, GSemikozov approved these changes

2021-07-06 09:36 UTC, merged