01_butoon
js-tasks-ru/htmlcss-20210610_drdiz pull request #5
Opened 2021-06-15 12:50 UTC by DoppelGannger

created button

2021-06-15 12:51 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-15 19:48 UTC, GSemikozov requested changes

2021-06-15 19:48 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button-list {
.button-list + .button-list_button - не относятся к боку .button; по сути, речь о другом отдельном блоке .button-list, и наша задача либо вынести эти стили в отдельный файл стилей в папку components, либо - если эти стили будут использоваться лишь для примерного размещения кнопок в хтмл-файле задачи и больше нигде - можно прямо в теге style в html файле задачи

2021-06-15 19:48 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    padding: 0%;
здесь и чуть ниже - нулевым значениям указывать единицы измерения не нужно

2021-06-15 19:48 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    width: 20%;
ширину блоку в данном случае лучше так не задавать (если будет встраивать кнопку в другой блок, например в карточку, то там кнопка будет оооочень маленькой) - лучше пусть будет display: inline-block и ширина кнопки определяется ее внутренним содержимым

2021-06-15 19:48 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    box-shadow: rgb(0 0 0 / 22%) 1px 7px 10px;
лучше значение просто скопировать из фигмы)

2021-06-15 19:48 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    height: 70px;
в дизайне, мне кажется, высота кнопки не такая большая)

2021-06-15 19:48 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    background-color: thistle;
договоримся цвета никогда текстом не задавать, только кодом (hex, rgb, hsl)

2021-06-15 19:48 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button__label {
вообще, стили для шрифта можно определить прямо в классе блока - поскольку они будут использоваться во всех типах кнопок. Но если бы хотелось сделать дополнительный внутренний враппер для текста, например через span - можно использовать элемент блока кнопки .button__label. Но тогда в коде - элемент блока не может быть на одном уровне с самим блоком - он всегда является его потомком. Поэтому было бы как-то так: `<button class="button"><span class="button__label"></span></button>`

2021-06-15 19:48 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    transition: 0.5s ease-in-out;
чтобы не дублировать в каждом модификаторе, лучше 1 раз задать сразу в блоке .button

2021-06-15 19:48 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    background-color: var(--white);
у primary кнопки на ховере фон не был, а оттенок синего. Ну и цвет шрифта ниже соответственно тоже указан неверно

2021-06-15 19:48 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    background-color: var(--white);
то же самое что и для primary выше

2021-06-15 19:48 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    color: var(--yellow);
и тут...
пусть :active полностью соответствует :hover-у

2021-06-15 19:48 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    background-color: var(--disable);
здесь можно всё удалить и оставить только `opacity: 0.5; pointer-events: none`

2021-06-16 07:51 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-16 09:07 UTC, GSemikozov requested changes

2021-06-16 09:07 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    padding-right: 3%;
паддинги пока договоримся задавать через пиксели - пока мы еще не изучили тему по адаптивности.

2021-06-16 09:10 UTC, DoppelGannger commented on 03-lection1/01-button/button.css
> +.button-list {
принял

2021-06-16 09:10 UTC, DoppelGannger commented on 03-lection1/01-button/button.css
> +    padding: 0%;
принял-пофиксил

2021-06-16 09:10 UTC, DoppelGannger commented on 03-lection1/01-button/button.css
> +    background-color: thistle;
принял-пофиксил

2021-06-16 09:10 UTC, DoppelGannger commented on 03-lection1/01-button/button.css
> +    width: 20%;
принял-пофиксил

2021-06-16 09:10 UTC, DoppelGannger commented on 03-lection1/01-button/button.css
> +    height: 70px;
принял-пофиксил

2021-06-16 09:10 UTC, DoppelGannger commented on 03-lection1/01-button/button.css
> +    box-shadow: rgb(0 0 0 / 22%) 1px 7px 10px;
принял-пофиксил

2021-06-16 09:10 UTC, DoppelGannger commented on 03-lection1/01-button/button.css
> +.button__label {
принял-пофиксил

2021-06-16 09:10 UTC, DoppelGannger commented on 03-lection1/01-button/button.css
> +    transition: 0.5s ease-in-out;
принял-пофиксил

2021-06-16 09:10 UTC, DoppelGannger commented on 03-lection1/01-button/button.css
> +    background-color: var(--white);
принял-пофиксил

2021-06-16 09:10 UTC, DoppelGannger commented on 03-lection1/01-button/button.css
> +    background-color: var(--white);
принял-пофиксил

2021-06-16 09:10 UTC, DoppelGannger commented on 03-lection1/01-button/button.css
> +    color: var(--yellow);
принял-пофиксил

2021-06-16 09:10 UTC, DoppelGannger commented on 03-lection1/01-button/button.css
> +    background-color: var(--disable);
принял-пофиксил

2021-06-16 09:10 UTC, DoppelGannger commented on 03-lection1/01-button/button.css
> +    padding-right: 3%;
принял

2021-06-16 09:24 UTC, DoppelGannger reviewed
принял-пофиксил

2021-06-16 09:35 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-16 10:20 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-16 11:20 UTC, GSemikozov approved these changes

2021-06-16 11:20 UTC, merged