'main-page-v0'
js-tasks-ru/htmlcss-20210610_drdiz pull request #8
Opened 2021-06-17 13:28 UTC by DoppelGannger

created main page

2021-06-17 13:29 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-17 15:42 UTC, GSemikozov requested changes

2021-06-17 15:42 UTC, GSemikozov commented on components/page/page.css
> +    margin: 0;
выше через абсолютный селектор уже всем элементам обнулили отступы)

2021-06-17 15:42 UTC, GSemikozov commented on components/page/page.css
> +.page_box {
это элемент, не модификатор, поэтому надо через 2 нижних подчеркивания `__`

2021-06-17 15:42 UTC, GSemikozov commented on components/page/page.css
> +.main {
.main, .header & .footer - это отдельные блоки, поэтому их надо вынести в отдельные компоненты.
если бы эти блоки были элементами блока page - мы бы писали `.page__header` и т.д.

2021-06-17 15:42 UTC, GSemikozov commented on components/page/page.css
> +.header__container h1 {
вместо вложенных селекторов + селектор тега по БЭМ мы бы хотели использовать более плоскую структуру на классах, поэтому - просто `.header__title`

2021-06-17 15:42 UTC, GSemikozov commented on components/page/page.css
> +.footer__text h2 {
то же самое - это по-видимому .footer__title

2021-06-17 15:42 UTC, GSemikozov commented on components/page/page.css
> +.footer__text p {
а это - просто .footer__text

2021-06-18 07:08 UTC, DoppelGannger commented on components/page/page.css
> +.main {
фикс

2021-06-18 07:11 UTC, DoppelGannger commented on components/page/page.css
> +.page_box {
фикс

2021-06-18 07:29 UTC, DoppelGannger commented on components/page/page.css
> +.header__container h1 {
фикс

2021-06-18 07:29 UTC, DoppelGannger commented on components/page/page.css
> +.footer__text h2 {
фикс

2021-06-18 07:30 UTC, DoppelGannger commented on components/page/page.css
> +.footer__text p {
фикс

2021-06-18 07:36 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-18 08:19 UTC, GSemikozov approved these changes

2021-06-18 08:19 UTC, merged